version: '3.8'


name: myfirst_docker_compose


services:
  web:
    image: nginx
    container_name: myfirst_nginx
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=8080
    volumes:
      - type: volume
        source: db-data
        target: /data
        volume:
          nocopy: true
    configs:
      - nginx-config
    ports:
      - "8081:80"
    networks:
      - app-network
    init: true
    restart: always


  db:
    image: mysql:latest
    container_name: myfirst_mysql
    volumes:
      - type: volume
        source: db-data
        target: /data
        volume:
          nocopy: true
    environment:
      MYSQL_ROOT_PASSWORD: root
    configs:
      - source: mysql-config
        target: /etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
    networks:
      - app-network
    init: true
    restart: always


configs:
  nginx-config:
    file: ./nginx.conf
  mysql-config:
    file: ./my.conf


volumes:
  db-data:


networks:
  app-network:
    driver: bridge